### ISSUE TITLE
Error creating account on red.segs.io

### ISSUE THREAD

**Issue by ZopharShinta** [Segs/Segs.io#30]
I'm getting a hash error trying to create an account through https://red.segs.io/register.cgi

![SegsRedError](https://user-images.githubusercontent.com/43687491/55446737-7ea17580-5586-11e9-8191-eb7a7478bf84.PNG)

**Comment by ldilley** [comment]
When @miles200 reverted to a prior release and rebuilt, the `dbtool.exe` hash changed. Whenever the binary is modified, the hash needs to be updated in `register.cgi` under the web directory. It is an added layer of security for now as we would not want to execute something that has potentially been tampered with. In the future, we'll likely use SQL queries instead of executing `dbtool` directly to avoid having to do this. The hash has been updated and registration is working properly again.

**Comment by miles200** [comment]
Good to know, thanks Dilleys!
