### ISSUE TITLE
Setup CI for Segs/Segs-Client repo

### ISSUE THREAD

**Issue by broxen** [Segs/Segs.io#57]
We need to setup Travis and Appveyor for Segs/Segs-Client repo now that we have a PR staged for SEGSLauncher v1

I don't have the powah (the Travis and Appveyor creds), so I'm punting this over to LD or Nem.

**Comment by HeraldOfOmega** [comment]
But if you got street cred, you could use that instead, couldn't you?

**Comment by ldilley** [comment]
Hm. You should've had the ability to modify this, @broxen, since you are an admin and owner of the `Segs` organization. I've added all repos within the org. For reference, if you click on Travis under https://github.com/organizations/Segs/settings/installations, it should allow you to select individual repos or all current and future repos. I've selected the latter and see the repos in Travis now at least. It looks like this was already set for AppVeyor.

Both apps should also let you login via GitHub OAuth on their respective sites and see that you are an organization owner. Are you seeing what you were expecting now, sir?

**Comment by broxen** [comment]
Yes. I do see it now. For some reason it wasn't showing before
